[project]
name = "test-usd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyopengl>=3.1.9",
    "pyside6>=6.9.1",
]
